apiVersion: batch/v1
kind: Job
metadata:
  name: apache-benchmark
spec:
  template:
    spec:
      containers:
        - name: apache-benchmark
          image: httpd
          command:
            [
              "ab",
              "-n",
              "5000000",
              "-c",
              "1000",
              "http://hpa-demo-service-nginx.default.svc.cluster.local/",
            ]
      restartPolicy: Never
  backoffLimit: 4
