apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec: 
  containers:
    - name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
        - containerPort: 80
          name: phpmyadmin
---
apiVersion: v1
kind: Service
metadata: 
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin 
  ports: 
    - port: 80  
  clusterIP: None